# Generated by Django 5.1.1 on 2025-11-08 01:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
            ],
            options={
                'db_table': 'catalog"."category_closure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryFacet',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('ord', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'catalog"."category_facet',
                'ordering': ['ord', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryFacetOption',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('ord', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('default_unit', models.TextField(blank=True, null=True)),
                ('geom_hint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'catalog"."category_facet_option',
                'ordering': ['facet__ord', 'ord', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('level', models.SmallIntegerField()),
                ('ord', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('org_unit_id', models.UUIDField(blank=True, null=True)),
                ('geom_hint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'catalog"."category_node',
                'ordering': ['level', 'ord', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryOptionRule',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'catalog"."category_option_rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryOptionSet',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('level_no', models.SmallIntegerField()),
                ('ord', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'catalog"."category_option_set',
                'ordering': ['l2__ord', 'level_no'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'catalog"."category_parent',
                'managed': False,
            },
        ),
    ]
