# Generated by Django 5.1.1 on 2025-12-03 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOptionPick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_no', models.SmallIntegerField()),
                ('ord', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog"."category_option_pick',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categoryparent',
            options={'managed': False, 'ordering': ()},
        ),
    ]
