from __future__ import annotations

from typing import Any


QGIS_MANIFEST_VERSION = "0.4"
QGIS_TRANSPORT_MODE = "server_gpkg_editable_snapshot"


def build_qgis_manifest(
    *,
    project: dict[str, Any],
    plan: dict[str, Any],
    can_write: bool,
    package_url: str,
    package_layers: list[dict[str, Any]],
    layer_counts: dict[str, int | None] | None = None,
    sync_url: str = "",
    sync_supported: bool = False,
) -> dict[str, Any]:
    """Build the server-authoritative QGIS GeoPackage manifest.

    One project-scoped GeoPackage is generated by GeoFlow Server from the same
    business-scope/Profile Layer Plan used by WebGIS. The package contains no
    database credentials. Local QGIS editing may be enabled when the current
    user has project write authority. Sync is separately gated server-side and
    currently enabled only for the strict development runtime.
    """

    project_id = str(project["id"])
    counts = layer_counts or {}
    layers = []
    for row in package_layers:
        standard_name = str(row["standard_name"])
        layers.append(
            {
                **row,
                "row_count": counts.get(standard_name),
                "primary_key": "id",
                "local_fid": "fid",
                "geometry_column": "geom",
                "source_srid": "EPSG:4326",
            }
        )

    effective_sync = bool(sync_supported and can_write and sync_url)
    return {
        "manifest_version": QGIS_MANIFEST_VERSION,
        "transport": {
            "mode": QGIS_TRANSPORT_MODE,
            "server_authoritative": True,
            "direct_postgis_credentials_exposed": False,
            "package_url": package_url,
            "package_format": "GeoPackage",
            "package_downloads_per_open": 1,
            "local_editing_supported": bool(can_write),
            "sync_supported": effective_sync,
            "sync_url": sync_url if effective_sync else "",
            "write_authorized": bool(can_write),
            "note": (
                "GeoFlow materializes one project-scoped editable GeoPackage. "
                "Sync is server-authorized and development-gated in this increment."
            ),
        },
        "project": {
            "id": project_id,
            "code": project.get("code") or "",
            "name": project.get("name") or "",
            "status": project.get("status") or "",
        },
        "profile": plan.get("profile"),
        "capabilities": plan.get("capabilities") or [],
        "layers": layers,
        "layer_count": len(layers),
        "qfield": {
            "package_supported": False,
            "reason": "qgis_gpkg_sync_mvp_before_qfield",
        },
    }
