"""
Django settings for geoflow_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from dotenv import load_dotenv

from .env_values import (
    get_optional_env_int,
    get_optional_env_text,
    get_optional_env_text_mapping,
)

logger = logging.getLogger("geoflow.env")

# Django 표준: BASE_DIR = manage.py가 있는 프로젝트 루트
BASE_DIR = Path(__file__).resolve().parent.parent

# .env는 프로젝트 루트에 둔다: C:\GeoFlow\geoflow_web\.env
DOTENV_PATH = BASE_DIR / ".env"

# override=False: OS 환경변수가 있으면 OS 값 우선, .env는 보조
load_dotenv(dotenv_path=DOTENV_PATH, override=False)
logger.debug("ENV: dotenv loading completed")


def get_env_required(name: str) -> str:
    value = os.getenv(name)
    if value is None or value == "":
        raise RuntimeError(f"Required environment variable is missing: {name}")
    return value


def get_env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None or value.strip() == "":
        return default
    return value.strip().lower() in ("1", "true", "yes", "y", "on")


def get_env_list(name: str, default: str = "") -> list[str]:
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_required("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = get_env_list("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = get_env_list("DJANGO_CSRF_TRUSTED_ORIGINS", default="")

# 기본값은 운영 보안 우선(secure=True), 로컬 http 개발 시 .env에서 False로 오버라이드
CSRF_COOKIE_SECURE = get_env_bool("DJANGO_CSRF_COOKIE_SECURE", default=True)
SESSION_COOKIE_SECURE = get_env_bool("DJANGO_SESSION_COOKIE_SECURE", default=True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'control',
    'control.gf_authz',
    'control.catalog',
    'geoflow_ops.apps.GeoflowOpsConfig',
    'django.contrib.humanize',
]

# -------------------------------------------------------------------
# GeoDjango 라이브러리 체크 (Windows)
# -------------------------------------------------------------------
# PostGIS 백엔드를 사용하는 경우 GDAL/GEOS가 필요합니다.
# 로드 실패 시 경고 로그를 출력하지만, 엔진은 변경하지 않습니다.
# 진단: python scripts/check_geodjango.py

def _check_geodjango_libraries():
    """GeoDjango 라이브러리 로드 가능 여부 체크 (경고만)"""
    gdal_ok = False
    geos_ok = False

    try:
        from django.contrib.gis import gdal
        gdal_ok = True
    except (ImportError, OSError):
        logger.warning("GeoDjango GDAL library unavailable")

    try:
        from django.contrib.gis import geos
        geos_ok = True
    except (ImportError, OSError):
        logger.warning("GeoDjango GEOS library unavailable")

    if not gdal_ok or not geos_ok:
        logger.warning("GeoDjango runtime libraries require attention")
    else:
        logger.info("GeoDjango 라이브러리 정상 로드 (GDAL: OK, GEOS: OK)")

# Windows에서만 체크 (Linux/Mac은 일반적으로 자동 설치됨)
if os.name == 'nt':
    _check_geodjango_libraries()

DATABASE_ROUTERS = ['control.db_router.TenantRouter']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'control.middleware.CentralAccountActiveGuardMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'control.middleware.TenantMembershipFreshnessGuardMiddleware',
    'control.middleware.TenantMiddleware',           # A. alias/scope 설정
    'control.middleware.CentralGuardMiddleware',     # B. 중앙이면 테넌트 URL 차단  ✅ 추가
    'control.middleware.EnsureTenantAliasMiddleware', # C. 안전망
    'control.gf_authz.middleware.GFAuthzContextMiddleware',
]

# 중앙 DB 별칭(기본이 중앙이면 그대로 'default')

# gf_authz가 사용할 중앙 테이블 경로(스키마.테이블)
GF_AUTHZ_TABLES = {
    "roles":            "public.roles",
    "permissions":      "public.permissions",
    "role_permissions": "public.role_permissions",

    # 여기! 우리는 사용자→그룹(=테넌트) 역할 배정 테이블로
    # public.user_group_map 을 표준으로 씁니다.
    "user_roles":       "public.user_group_map",

    # 프로젝트 단위 스코프가 필요할 때만 열어두세요(없으면 주석)
    # "project_members":  "public.user_project_members",
}


ROOT_URLCONF = 'geoflow_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # "DIRS": [ BASE_DIR / "templates" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'control.context_processors.central_flags',
                "control.context_processors.perms_context",
                "control.context_processors.avatar_context",
                "geoflow_ops.context_processors.topbar_user",
                'control.gf_authz.context_processors.gf_authz',
            ],
        },
    },
]

WSGI_APPLICATION = 'geoflow_project.wsgi.application'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"

CENTRAL_DB_ALIAS = "default"            # 중앙 DB 별칭
# gf_authz에서 사용할 중앙 DB 별칭 (CENTRAL_DB_ALIAS와 동일하게 유지)
GF_AUTHZ_CENTRAL_ALIAS = CENTRAL_DB_ALIAS

DEFAULT_TENANT_DB_ALIAS = "cheonan_db"  # 테넌트 앱 마이그레이션/초기화용 기본 테넌트 DB (런타임 기본은 CENTRAL_DB_ALIAS)

# 중앙(Control) DB 접속 정보
CENTRAL_DB_NAME = os.getenv("CENTRAL_DB_NAME", "geoflow_control")
CENTRAL_DB_USER = os.getenv("CENTRAL_DB_USER", "geoflow_admin")
CENTRAL_DB_PASSWORD = os.getenv("CENTRAL_DB_PASSWORD", "")
CENTRAL_DB_HOST = os.getenv("CENTRAL_DB_HOST", "localhost")
CENTRAL_DB_PORT = os.getenv("CENTRAL_DB_PORT", "5432")


# 테넌트 인사 프로필
TENANT_PROFILE_VIEW = "people_profile"          # 조회 전용
TENANT_PROFILE_TABLE = "hr.employee_profile"    # 쓰기/업서트 대상

# -------------------------------------------------------------------
# Tenant DB Credentials (테넌트 DB 접속 계정)
# -------------------------------------------------------------------
# Fallback 순서:
#   1. TENANT_DB_USER/PASSWORD/HOST/PORT (전용 계정)
#   2. PROVISIONER_DB_USER/PASSWORD/HOST/PORT (프로비저닝 계정)
#   3. CENTRAL_DB_USER/PASSWORD/HOST/PORT (중앙 DB 기본값)
# 확인: python manage.py shell -c "from django.conf import settings; print(settings.DATABASES['cheonan_db'])"

TENANT_DB_NAME = os.getenv("TENANT_DB_NAME", "cheonan_db")
TENANT_DB_USER = os.getenv("TENANT_DB_USER") or os.getenv("PROVISIONER_DB_USER") or CENTRAL_DB_USER
TENANT_DB_PASSWORD = os.getenv("TENANT_DB_PASSWORD") or os.getenv("PROVISIONER_DB_PASSWORD") or CENTRAL_DB_PASSWORD
TENANT_DB_HOST = os.getenv("TENANT_DB_HOST") or os.getenv("PROVISIONER_DB_HOST") or CENTRAL_DB_HOST
TENANT_DB_PORT = os.getenv("TENANT_DB_PORT") or os.getenv("PROVISIONER_DB_PORT") or CENTRAL_DB_PORT

# 경고: 중요 설정이 빈 문자열일 경우
if not TENANT_DB_USER:
    logger.warning("Tenant database user configuration is unavailable")
if not TENANT_DB_PASSWORD:
    logger.warning("Tenant database password configuration is unavailable")
if not TENANT_DB_HOST or TENANT_DB_HOST == "localhost":
    logger.warning("Tenant database host uses local or unavailable configuration")
if not TENANT_DB_PORT or TENANT_DB_PORT == "5432":
    logger.info("Tenant database port uses default configuration")

# 테넌트 DB 프로비저닝/검증용 기본 템플릿(실제 생성/마이그레이션은 별도 로직에서 수행)
TENANT_DB_TEMPLATE = {
    "ENGINE": "django.contrib.gis.db.backends.postgis",
    "HOST": TENANT_DB_HOST,
    "PORT": int(TENANT_DB_PORT),
    "USER": TENANT_DB_USER,
    "PASSWORD": TENANT_DB_PASSWORD,
}

# -------------------------------------------------------------------
# Provisioner DB Credentials (프로비저닝 전용)
# -------------------------------------------------------------------

def _getenv(name: str, default: str = "") -> str:
    v = os.getenv(name, default)
    return (v or "").strip()

PROVISIONER_DB_HOST = _getenv("PROVISIONER_DB_HOST", "")
PROVISIONER_DB_PORT = _getenv("PROVISIONER_DB_PORT", "")
PROVISIONER_DB_USER = _getenv("PROVISIONER_DB_USER", "")
PROVISIONER_DB_PASSWORD = _getenv("PROVISIONER_DB_PASSWORD", "")

# 1-B 안전장치:
# - 기본: 프로비저닝 기능은 꺼져있음(ENABLE_TENANT_PROVISIONING=1일 때만 ON)
# - ON 상태인데 필수 값이 없으면 즉시 중단(“조용히 실패” 방지)
ENABLE_TENANT_PROVISIONING = _getenv("ENABLE_TENANT_PROVISIONING", "0") in ("1", "true", "True", "yes", "YES")

_missing = []
if not PROVISIONER_DB_HOST: _missing.append("PROVISIONER_DB_HOST")
if not PROVISIONER_DB_PORT: _missing.append("PROVISIONER_DB_PORT")
if not PROVISIONER_DB_USER: _missing.append("PROVISIONER_DB_USER")
if not PROVISIONER_DB_PASSWORD: _missing.append("PROVISIONER_DB_PASSWORD")

PROVISIONING_READY = (len(_missing) == 0)

if ENABLE_TENANT_PROVISIONING and not PROVISIONING_READY:
    raise RuntimeError(
        "Tenant provisioning is ENABLED but missing env vars: "
        + ", ".join(_missing)
    )

if not ENABLE_TENANT_PROVISIONING:
    logger.info("Provisioning disabled (ENABLE_TENANT_PROVISIONING!=1).")
elif PROVISIONING_READY:
    logger.info("Provisioning enabled and READY (PROVISIONER_* present).")


DATABASES = {
    "default": {  # 중앙
        "ENGINE": "django.db.backends.postgresql",
        "NAME": CENTRAL_DB_NAME,
        "USER": CENTRAL_DB_USER,
        "PASSWORD": CENTRAL_DB_PASSWORD,
        "HOST": CENTRAL_DB_HOST,
        "PORT": CENTRAL_DB_PORT,
        "OPTIONS": {
            "sslmode": "require",   # verify-full 사용 중이면 pem 경로 그대로 두셔도 됩니다
            # "sslrootcert": os.path.join(BASE_DIR, "rds-combined-ca-bundle.pem"),
        },
        "ATOMIC_REQUESTS": False,
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": False,
    },
    "cheonan_db": {  # 테넌트
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": TENANT_DB_NAME,
        "USER": TENANT_DB_USER,
        "PASSWORD": TENANT_DB_PASSWORD,
        "HOST": TENANT_DB_HOST,
        "PORT": TENANT_DB_PORT,
        "OPTIONS": {
            "sslmode": "require",
            # "sslrootcert": os.path.join(BASE_DIR, "rds-combined-ca-bundle.pem"),
        },
        "ATOMIC_REQUESTS": False,
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": False,
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",          # 기본(신규 저장은 이것)
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",     # 과거 bcrypt 읽기용
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'control', 'static') ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend selection:
# - If USE_SMTP_EMAIL=1 in environment, force SMTP backend regardless of DEBUG
# - Otherwise, preserve behavior: DEBUG -> console backend, else SMTP backend
USE_SMTP_EMAIL = os.getenv("USE_SMTP_EMAIL", "") == "1"
if USE_SMTP_EMAIL:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    if DEBUG:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# 기본 SMTP 설정(환경에 맞게 오버라이드 권장)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.example.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
SITE_ORIGIN = "http://192.168.0.19:8000"
DEFAULT_FROM_EMAIL = "noreply@geoflow.local"

# Signup verification remains disabled until all runtime values are configured.
# Key material is supplied only through the environment and is never logged.
SIGNUP_EMAIL_VERIFICATION_ACTIVE_KEY_ID = get_optional_env_text(
    os.environ,
    "SIGNUP_EMAIL_VERIFICATION_ACTIVE_KEY_ID",
)
SIGNUP_EMAIL_VERIFICATION_HMAC_KEYS = get_optional_env_text_mapping(
    os.environ,
    "SIGNUP_EMAIL_VERIFICATION_HMAC_KEYS_JSON",
)
SIGNUP_EMAIL_VERIFICATION_TTL_SECONDS = get_optional_env_int(
    os.environ,
    "SIGNUP_EMAIL_VERIFICATION_TTL_SECONDS",
    minimum=60,
    maximum=7 * 24 * 60 * 60,
)
SIGNUP_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS = get_optional_env_int(
    os.environ,
    "SIGNUP_EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS",
    minimum=60,
    maximum=24 * 60 * 60,
)

APPLICATION_DIAGNOSTIC_LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "formatters": {
        "simple": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"},
    },
    "loggers": {
        "control": {  # control.* 전역
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # 세부 모듈 별도 조절도 가능
        "control.middleware": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "control.views_auth": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "control.db_router": {
            "handlers": ["console"],
            "level": APPLICATION_DIAGNOSTIC_LOG_LEVEL,
            "propagate": False,
        },
        "geoflow_ops": {
            "handlers": ["console"],
            "level": APPLICATION_DIAGNOSTIC_LOG_LEVEL,
            "propagate": False,
        },
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
}