"""
Django settings for geoflow_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bi5!%5s2n5!1lg=i)g8bvrvrvq#h$-oe&6o8eb-opxkxves0f2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.0.19", "localhost", "127.0.0.1"]
CSRF_TRUSTED_ORIGINS = [
    "http://192.168.0.19",
    "http://192.168.0.19:8000",
    "http://127.0.0.1",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

# 로컬 개발환경에서만
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'control',
    'control.gf_authz',
    'control.catalog',
    'geoflow_ops.apps.GeoflowOpsConfig',
    'django.contrib.humanize',
]

DATABASE_ROUTERS = ['control.db_router.TenantRouter']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'control.middleware.TenantMiddleware',           # A. alias/scope 설정
    'control.middleware.CentralGuardMiddleware',     # B. 중앙이면 테넌트 URL 차단  ✅ 추가
    'control.middleware.EnsureTenantAliasMiddleware', # C. 안전망
    'control.gf_authz.middleware.GFAuthzContextMiddleware',
]

# 중앙 DB 별칭(기본이 중앙이면 그대로 'default')
GF_AUTHZ_CENTRAL_ALIAS = "default"

# gf_authz가 사용할 중앙 테이블 경로(스키마.테이블)
GF_AUTHZ_TABLES = {
    "roles":            "public.roles",
    "permissions":      "public.permissions",
    "role_permissions": "public.role_permissions",

    # 여기! 우리는 사용자→그룹(=테넌트) 역할 배정 테이블로
    # public.user_group_map 을 표준으로 씁니다.
    "user_roles":       "public.user_group_map",

    # 프로젝트 단위 스코프가 필요할 때만 열어두세요(없으면 주석)
    # "project_members":  "public.user_project_members",
}


ROOT_URLCONF = 'geoflow_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # "DIRS": [ BASE_DIR / "templates" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'control.context_processors.central_flags',
                "control.context_processors.perms_context",
                'control.gf_authz.context_processors.gf_authz',
            ],
        },
    },
]

WSGI_APPLICATION = 'geoflow_project.wsgi.application'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"

CENTRAL_DB_ALIAS = "default"            # 중앙 DB 별칭
DEFAULT_TENANT_DB_ALIAS = "cheonan_db"  # 세션이 비어있을 때 사용할 테넌트 기본값


# 테넌트 인사 프로필
TENANT_PROFILE_VIEW = "people_profile"          # 조회 전용
TENANT_PROFILE_TABLE = "hr.employee_profile"    # 쓰기/업서트 대상

DATABASES = {
    "default": {  # 중앙
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "geoflow_control",
        "USER": "geoflow_admin",
        "PASSWORD": "geoflow2025",
        "HOST": "geoflow-rds1.c5okm2mm22bu.ap-northeast-2.rds.amazonaws.com",
        "PORT": "5432",
        "OPTIONS": {
            "sslmode": "require",   # verify-full 사용 중이면 pem 경로 그대로 두셔도 됩니다
            # "sslrootcert": os.path.join(BASE_DIR, "rds-combined-ca-bundle.pem"),
        },
        "ATOMIC_REQUESTS": False,
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": False,
    },
    "cheonan_db": {  # 테넌트
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "cheonan_db",
        "USER": "cheonan_admin",
        "PASSWORD": "test1234",     # 타깃에서 만든 비밀번호 값으로
        "HOST": "geoflow-rds1.c5okm2mm22bu.ap-northeast-2.rds.amazonaws.com",
        "PORT": "5432",
        "OPTIONS": {
            "sslmode": "require",
            # "sslrootcert": os.path.join(BASE_DIR, "rds-combined-ca-bundle.pem"),
        },
        "ATOMIC_REQUESTS": False,
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": False,
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",          # 기본(신규 저장은 이것)
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",     # 과거 bcrypt 읽기용
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'control', 'static') ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # 콘솔 출력
SITE_ORIGIN = "http://192.168.0.19:8000"
DEFAULT_FROM_EMAIL = "noreply@geoflow.local"

RRN_SYM_KEY = "여러분의-강력한-대칭키"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "formatters": {
        "simple": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"},
    },
    "loggers": {
        "control": {  # control.* 전역
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # 세부 모듈 별도 조절도 가능
        "control.middleware": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "control.views_auth": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "control.db_router": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
        "geoflow_ops": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
}
