# Generated by Django 5.2.4 on 2025-08-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractmanagement',
            options={'managed': False},
        ),
    ]
