# Generated by Django 5.2.4 on 2025-08-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0002_alter_contractmanagement_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractmanagement',
            table='contract.contract_management',
        ),
    ]
