# Generated by Django 5.1.1 on 2025-09-11 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0003_alter_contractmanagement_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.BigIntegerField(blank=True, db_column='legacy_id', null=True)),
                ('code', models.TextField(blank=True, db_column='code', null=True)),
                ('name', models.TextField(db_column='name')),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
                ('amount', models.DecimalField(blank=True, db_column='amount', decimal_places=0, max_digits=14, null=True)),
                ('status', models.TextField(blank=True, db_column='status', null=True)),
                ('kind', models.TextField(blank=True, db_column='kind', null=True)),
                ('division', models.TextField(blank=True, db_column='division', null=True)),
                ('org_unit_id', models.UUIDField(blank=True, db_column='org_unit_id', null=True)),
                ('ext', models.JSONField(blank=True, db_column='ext', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='비고')),
            ],
            options={
                'db_table': '"ctr"."contracts"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('legacy_id', models.BigIntegerField(blank=True, db_column='legacy_id', null=True)),
                ('name', models.TextField(db_column='name')),
                ('type', models.TextField(blank=True, db_column='type', null=True)),
                ('biz_no', models.TextField(blank=True, db_column='biz_no', null=True)),
                ('rep_name', models.TextField(blank=True, db_column='rep_name', null=True)),
                ('phone', models.TextField(blank=True, db_column='phone', null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('address', models.TextField(blank=True, db_column='address', null=True)),
                ('status', models.TextField(blank=True, db_column='status', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': '"ctr"."partners"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrjCategory',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('level', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'cat"."prj_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, db_column='code', null=True)),
                ('name', models.TextField(db_column='name')),
                ('start_date', models.DateField(blank=True, db_column='start_date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True)),
                ('status', models.TextField(blank=True, db_column='status', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('org_unit_id', models.UUIDField(blank=True, db_column='org_unit_id', null=True)),
                ('ext', models.JSONField(blank=True, db_column='ext', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': '"prj"."projects"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'prj"."project_category',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ContractManagement',
        ),
    ]
