# Generated by Django 5.1.1 on 2025-12-03 07:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0004_contract_partner_prjcategory_project_projectcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrgUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('type', models.TextField(blank=True, db_column='type', null=True)),
                ('biz_no', models.TextField(blank=True, db_column='biz_no', null=True)),
                ('rep_name', models.TextField(blank=True, db_column='rep_name', null=True)),
                ('phone', models.TextField(blank=True, db_column='phone', null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('address', models.TextField(blank=True, db_column='address', null=True)),
                ('label', models.TextField(blank=True, db_column='label', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': '"ops"."my_org_units"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectScopeItem',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_column='project_id', help_text='프로젝트 ID (prj.projects.id)')),
                ('lv2_id', models.UUIDField(db_column='lv2_id', help_text='L2(CategoryNode.id) - 중분류')),
                ('lv3_id', models.UUIDField(blank=True, db_column='lv3_id', help_text='L3(CategoryFacetOption.id) - 세분류(옵션)', null=True)),
                ('lv4_id', models.UUIDField(blank=True, db_column='lv4_id', help_text='L4(CategoryFacetOption.id) - 세분류(옵션)', null=True)),
                ('unit', models.CharField(db_column='unit', help_text='단위 코드 (예: m, EA, ㎡ 등)', max_length=20)),
                ('design_qty', models.DecimalField(blank=True, db_column='design_qty', decimal_places=3, help_text='설계 수량/연장', max_digits=18, null=True)),
                ('completed_qty', models.DecimalField(blank=True, db_column='completed_qty', decimal_places=3, help_text='완료(실적) 수량/연장', max_digits=18, null=True)),
                ('remark', models.CharField(blank=True, db_column='remark', help_text='간단한 메모', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': '"prj"."scope_item"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PrjCategory',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
