# Generated by GPT-5.2 on 2025-12-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0005_myorgunit_projectscopeitem_delete_prjcategory_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS ops;

            CREATE TABLE IF NOT EXISTS ops.my_org_units (
                id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                name text NOT NULL,
                type text NULL,
                biz_no text NULL,
                rep_name text NULL,
                phone text NULL,
                email text NULL,
                address text NULL,
                label text NULL,
                description text NULL,
                created_at timestamptz NULL DEFAULT now(),
                updated_at timestamptz NULL DEFAULT now()
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
