# Generated by GPT-5.2 on 2025-12-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0006_create_ops_my_org_units_if_missing"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS ctr;
            CREATE SCHEMA IF NOT EXISTS prj;

            -- ctr.partners (minimal columns to satisfy current Django models/views)
            CREATE TABLE IF NOT EXISTS ctr.partners (
                id uuid PRIMARY KEY,
                legacy_id bigint NULL,
                name text NOT NULL,
                type text NULL,
                biz_no text NULL,
                rep_name text NULL,
                phone text NULL,
                email text NULL,
                address text NULL,
                status text NULL,
                description text NULL,
                created_at timestamptz NULL,
                updated_at timestamptz NULL
            );

            -- ctr.contracts
            CREATE TABLE IF NOT EXISTS ctr.contracts (
                id uuid PRIMARY KEY,
                legacy_id bigint NULL,
                code text NULL,
                name text NOT NULL,
                start_date date NULL,
                end_date date NULL,
                amount numeric(14, 0) NULL,
                status text NULL,
                kind text NULL,
                division text NULL,
                client_id uuid NULL,
                sub_client_id uuid NULL,
                org_unit_id uuid NULL,
                ext jsonb NULL,
                created_at timestamptz NULL,
                updated_at timestamptz NULL,
                description text NULL
            );

            -- prj.projects
            CREATE TABLE IF NOT EXISTS prj.projects (
                id uuid PRIMARY KEY,
                contract_id uuid NULL,
                code text NULL,
                name text NULL,
                start_date date NULL,
                end_date date NULL,
                status text NULL,
                description text NULL,
                org_unit_id uuid NULL,
                ext jsonb NULL,
                created_at timestamptz NULL,
                updated_at timestamptz NULL
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
