# Generated by GPT-5.2 on 2025-12-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0007_create_ctr_prj_core_tables_if_missing"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS hr;

            -- hr.employee_profile
            -- NOTE: views_employees.py uses raw SQL and expects these columns to exist.
            CREATE TABLE IF NOT EXISTS hr.employee_profile (
                id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                email text NULL,
                name text NULL,
                title text NULL,
                role_code text NULL,
                status text NULL,
                phone text NULL,

                hire_date date NULL,
                term_date date NULL,

                org_unit_id uuid NULL,
                department_id uuid NULL,
                position_grade text NULL,
                emp_type text NULL,
                emp_no text NULL,
                manager_id uuid NULL,

                rrn_cipher bytea NULL,
                rrn_hash bytea NULL,
                rrn_last4 text NULL,

                central_user_id uuid NULL,

                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now()
            );

            -- hr.departments
            CREATE TABLE IF NOT EXISTS hr.departments (
                id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                org_unit_id uuid NULL,
                name text NULL,
                active boolean NOT NULL DEFAULT true,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now()
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
