# Generated by GPT-5.2 on 2025-12-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0008_create_hr_tables_if_missing"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS prj;

            -- prj.scope_item
            -- NOTE: ProjectScopeItem model (managed=False) expects columns like lv2_id/lv3_id/lv4_id/unit/design_qty/completed_qty.
            -- Extra columns (code/name/ord/active) are kept nullable/defaulted for forward-compat.
            CREATE TABLE IF NOT EXISTS prj.scope_item (
                id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

                project_id uuid NULL,

                code text NULL,
                name text NULL,

                lv2_id uuid NULL,
                lv3_id uuid NULL,
                lv4_id uuid NULL,

                unit varchar(20) NULL,
                design_qty numeric(18, 3) NULL,
                completed_qty numeric(18, 3) NULL,
                remark varchar(255) NULL,

                ord integer NOT NULL DEFAULT 0,
                active boolean NOT NULL DEFAULT true,

                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now()
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
