# Generated by GPT-5.2 on 2025-12-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0009_create_prj_scope_item_if_missing"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1) Required extension
            CREATE EXTENSION IF NOT EXISTS citext;

            -- 2) Standardize email columns to citext (only if table/column exists)
            DO $$
            BEGIN
              IF to_regclass('ctr.partners') IS NOT NULL THEN
                IF EXISTS (
                  SELECT 1
                    FROM information_schema.columns
                   WHERE table_schema='ctr'
                     AND table_name='partners'
                     AND column_name='email'
                ) THEN
                  EXECUTE 'ALTER TABLE ctr.partners ALTER COLUMN email TYPE citext USING email::citext';
                END IF;
              END IF;

              IF to_regclass('ops.my_org_units') IS NOT NULL THEN
                IF EXISTS (
                  SELECT 1
                    FROM information_schema.columns
                   WHERE table_schema='ops'
                     AND table_name='my_org_units'
                     AND column_name='email'
                ) THEN
                  EXECUTE 'ALTER TABLE ops.my_org_units ALTER COLUMN email TYPE citext USING email::citext';
                END IF;
              END IF;
            END $$;

            -- 3) Drop unneeded columns (only if table exists)
            DO $$
            BEGIN
              IF to_regclass('prj.scope_item') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE prj.scope_item '
                     || 'DROP COLUMN IF EXISTS code, '
                     || 'DROP COLUMN IF EXISTS name, '
                     || 'DROP COLUMN IF EXISTS ord, '
                     || 'DROP COLUMN IF EXISTS active';
              END IF;

              IF to_regclass('hr.employee_profile') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE hr.employee_profile DROP COLUMN IF EXISTS user_id';
              END IF;

              IF to_regclass('prj.projects') IS NOT NULL THEN
                EXECUTE 'ALTER TABLE prj.projects DROP COLUMN IF EXISTS legacy_key';
              END IF;
            END $$;

            -- 4) View recreation safety: drop hr.v_employee_profile_safe if it exists.
            -- NOTE: The canonical VIEW definition should live in a dedicated baseline SQL file.
            DO $$
            BEGIN
              IF to_regclass('hr.v_employee_profile_safe') IS NOT NULL THEN
                EXECUTE 'DROP VIEW hr.v_employee_profile_safe';
              END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
