# Generated by GPT-5.2 on 2025-12-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0010_tenant_schema_maintenance_citext_cleanup"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Ensure ops.schema_version exists (tenant DB baseline)
            -- Idempotent: CREATE TABLE IF NOT EXISTS + INSERT ... ON CONFLICT DO NOTHING
            -- (Human reference: geoflow_ops/sql/ops_schema_version.sql)
            CREATE SCHEMA IF NOT EXISTS ops;

            CREATE TABLE IF NOT EXISTS ops.schema_version (
              id          smallint PRIMARY KEY DEFAULT 1,
              version     integer  NOT NULL,
              applied_at  timestamptz NOT NULL DEFAULT now(),
              CONSTRAINT schema_version_single_row CHECK (id = 1)
            );

            INSERT INTO ops.schema_version (id, version, applied_at)
            VALUES (1, 1, now())
            ON CONFLICT (id) DO NOTHING;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
