# Generated by GPT-5.2 on 2025-12-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0011_create_ops_schema_version_if_missing"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Install ops.bump_schema_version(target_version) utility
            CREATE SCHEMA IF NOT EXISTS ops;

            CREATE TABLE IF NOT EXISTS ops.schema_version (
              id          smallint PRIMARY KEY DEFAULT 1,
              version     integer  NOT NULL,
              applied_at  timestamptz NOT NULL DEFAULT now(),
              CONSTRAINT schema_version_single_row CHECK (id = 1)
            );

            INSERT INTO ops.schema_version (id, version, applied_at)
            VALUES (1, 1, now())
            ON CONFLICT (id) DO NOTHING;

            CREATE OR REPLACE FUNCTION ops.bump_schema_version(target_version integer)
            RETURNS void
            LANGUAGE plpgsql
            AS $$
            DECLARE
              current_version integer;
            BEGIN
              IF target_version IS NULL OR target_version < 1 THEN
                RAISE EXCEPTION 'target_version must be >= 1 (got=%)', target_version;
              END IF;

              SELECT version INTO current_version
                FROM ops.schema_version
               WHERE id = 1;

              IF current_version IS NULL THEN
                INSERT INTO ops.schema_version (id, version, applied_at)
                VALUES (1, 1, now())
                ON CONFLICT (id) DO NOTHING;

                SELECT version INTO current_version
                  FROM ops.schema_version
                 WHERE id = 1;
              END IF;

              IF current_version IS NULL THEN
                RAISE EXCEPTION 'ops.schema_version row(id=1) is missing';
              END IF;

              IF current_version >= target_version THEN
                RETURN;
              END IF;

              IF current_version <> target_version - 1 THEN
                RAISE EXCEPTION 'unexpected schema_version %, expected % (target=%)',
                  current_version, target_version - 1, target_version;
              END IF;

              UPDATE ops.schema_version
                 SET version = target_version,
                     applied_at = now()
               WHERE id = 1;
            END;
            $$;

            -- Example:
            --   SELECT ops.bump_schema_version(2);  -- 1 -> 2 bump
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
