# Generated by GPT-5.2 on 2025-12-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0012_add_ops_schema_version_bump_function"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Install ops.schema_version_bump(target_version) wrapper.
            --
            -- Policy:
            --   - Out-of-order bump is blocked.
            --   - Must be called after DDL changes.
            --
            -- NOTE:
            --   ops.bump_schema_version already exists (0012) but the project
            --   standardizes on ops.schema_version_bump for migrations/templates.

            CREATE SCHEMA IF NOT EXISTS ops;

            CREATE OR REPLACE FUNCTION ops.schema_version_bump(target_version integer)
            RETURNS void
            LANGUAGE plpgsql
            AS $$
            DECLARE
              current_version integer;
            BEGIN
              IF target_version IS NULL OR target_version < 1 THEN
                RAISE EXCEPTION 'target_version must be >= 1 (got=%)', target_version;
              END IF;

              SELECT version INTO current_version
                FROM ops.schema_version
               WHERE id = 1;

              IF current_version IS NULL THEN
                RAISE EXCEPTION 'ops.schema_version row(id=1) is missing';
              END IF;

              IF current_version >= target_version THEN
                RETURN;
              END IF;

              IF current_version <> target_version - 1 THEN
                RAISE EXCEPTION 'unexpected schema_version %, expected % (target=%)',
                  current_version, target_version - 1, target_version;
              END IF;

              UPDATE ops.schema_version
                 SET version = target_version,
                     applied_at = now()
               WHERE id = 1;
            END;
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
