# Generated by GPT-5.2 on 2026-01-04

from __future__ import annotations

import uuid

from django.db import migrations, models


TARGET_VERSION = 2


class Migration(migrations.Migration):

    dependencies = [
        ("webgisapp", "0013_add_ops_schema_version_bump_alias"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"""
                    -- hr.employee_profile: address fields (nullable)
                    ALTER TABLE IF EXISTS hr.employee_profile
                        ADD COLUMN IF NOT EXISTS addr_road   TEXT NULL,
                        ADD COLUMN IF NOT EXISTS addr_detail TEXT NULL,
                        ADD COLUMN IF NOT EXISTS addr_zip    VARCHAR(10) NULL;

                    -- Schema version bump (after DDL)
                    SELECT ops.schema_version_bump({TARGET_VERSION});
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="EmployeeProfile",
                    fields=[
                        ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                        ("email", models.TextField(blank=True, null=True)),
                        ("name", models.TextField(blank=True, null=True)),
                        ("title", models.TextField(blank=True, null=True)),
                        ("role_code", models.TextField(blank=True, null=True)),
                        ("status", models.TextField(blank=True, null=True)),
                        ("phone", models.TextField(blank=True, null=True)),
                        ("hire_date", models.DateField(blank=True, null=True)),
                        ("term_date", models.DateField(blank=True, null=True)),
                        ("org_unit_id", models.UUIDField(blank=True, null=True)),
                        ("department_id", models.UUIDField(blank=True, null=True)),
                        ("position_grade", models.TextField(blank=True, null=True)),
                        ("emp_type", models.TextField(blank=True, null=True)),
                        ("emp_no", models.TextField(blank=True, null=True)),
                        ("manager_id", models.UUIDField(blank=True, null=True)),
                        ("rrn_cipher", models.BinaryField(blank=True, null=True)),
                        ("rrn_hash", models.BinaryField(blank=True, null=True)),
                        ("rrn_last4", models.TextField(blank=True, null=True)),
                        ("central_user_id", models.UUIDField(blank=True, null=True)),
                        ("addr_road", models.TextField(blank=True, null=True)),
                        ("addr_detail", models.TextField(blank=True, null=True)),
                        ("addr_zip", models.CharField(max_length=10, blank=True, null=True)),
                        ("created_at", models.DateTimeField()),
                        ("updated_at", models.DateTimeField()),
                    ],
                    options={
                        "db_table": '"hr"."employee_profile"',
                        "managed": False,
                    },
                ),
            ],
        ),
    ]
