# Generated by Django 5.1.1 on 2026-01-08 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0005_myorgunit_projectscopeitem_delete_prjcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.TextField(db_column='entity_type')),
                ('entity_id', models.UUIDField(db_column='entity_id')),
                ('purpose', models.TextField(db_column='purpose')),
                ('object_key', models.TextField(db_column='object_key', unique=True)),
                ('original_name', models.TextField(db_column='original_name')),
                ('mime_type', models.TextField(blank=True, db_column='mime_type', null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, db_column='size_bytes', null=True)),
                ('sha256', models.TextField(blank=True, db_column='sha256', null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('ord', models.IntegerField(db_column='ord', default=0)),
                ('meta', models.JSONField(blank=True, db_column='meta', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': '"ops"."attachments"',
                'managed': True,
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_att_entity'), models.Index(fields=['entity_type', 'entity_id', 'purpose', 'ord'], name='idx_att_entity_purpose_ord')],
            },
        ),
    ]
