# Generated by Django 5.2.4 on 2026-01-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0015_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='deleted_by',
            field=models.TextField(blank=True, db_column='deleted_by', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
    ]
