# Generated by Django 5.2.4 on 2026-01-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0016_add_attachment_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='kind',
            field=models.TextField(db_column='kind', default='file'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='webgisapp.attachment'),
        ),
    ]
