# Generated by Django 5.2.4 on 2026-01-23 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0017_attachment_kind_attachment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(db_column='scope_type', help_text='contract, employee, orgunit 등', max_length=50)),
                ('scope_id', models.UUIDField(db_column='scope_id', help_text='해당 엔티티의 UUID')),
                ('stage', models.CharField(db_column='stage', help_text='업무 단계 (pre_contract, contract, closeout, onboarding 등)', max_length=50)),
                ('event_type', models.CharField(db_column='event_type', help_text='이벤트 유형 (estimate, contract_doc, license 등)', max_length=50)),
                ('title', models.CharField(blank=True, db_column='title', default='', help_text='이벤트 제목', max_length=255)),
                ('memo', models.TextField(blank=True, db_column='memo', default='', help_text='메모')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('done', 'Done'), ('void', 'Void')], db_column='status', default='draft', help_text='이벤트 상태', max_length=20)),
                ('occurred_at', models.DateField(blank=True, db_column='occurred_at', help_text='발생일', null=True)),
                ('due_at', models.DateField(blank=True, db_column='due_at', help_text='기한', null=True)),
                ('created_by', models.CharField(db_column='created_by', help_text='생성자 email 또는 user ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': '"ops"."process_events"',
                'managed': True,
                'indexes': [models.Index(fields=['scope_type', 'scope_id'], name='idx_event_scope'), models.Index(fields=['scope_type', 'scope_id', 'stage'], name='idx_event_scope_stage'), models.Index(fields=['status'], name='idx_event_status')],
            },
        ),
        migrations.CreateModel(
            name='ProcessEventAttachment',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('support', 'Support')], db_column='role', default='support', help_text='첨부 역할 (primary: 주문서, support: 참고자료)', max_length=20)),
                ('ord', models.PositiveIntegerField(db_column='ord', default=0, help_text='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('attachment', models.ForeignKey(db_column='attachment_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='webgisapp.attachment')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='webgisapp.processevent')),
            ],
            options={
                'db_table': '"ops"."process_event_attachments"',
                'managed': True,
                'indexes': [models.Index(fields=['event', 'ord'], name='idx_event_att_ord')],
                'constraints': [models.UniqueConstraint(fields=('event', 'attachment'), name='unique_event_attachment')],
            },
        ),
    ]
