# Generated by Django 5.2.16 on 2026-09-13 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_collectionjob_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='apibudget',
            name='inserted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apibudget',
            name='received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apibudget',
            name='updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='backfill_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='backfill_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='backfill_status',
            field=models.CharField(default='BACKFILL_PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='generation',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='incremental_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='last_incremental_success',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='local_match_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='local_match_cursor',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='collectionjob',
            name='local_matched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CollectionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.UUIDField()),
                ('mode', models.CharField(max_length=16)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('metrics', models.JSONField(default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='windows', to='procurement.collectionjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'generation', 'mode', 'start'], name='procurement_coverage_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'generation', 'mode', 'start', 'end'), name='procurement_window_unique')],
            },
        ),
    ]
