# Generated by Django 5.2.16 on 2026-09-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_apibudget_inserted_apibudget_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPeriod',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='procurement_period_singleton'), models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='procurement_period_order')],
            },
        ),
    ]
