# Generated by Django 5.1.1 on 2025-09-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'role_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('name_display', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroupMap',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_group_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDBConfig',
            fields=[
                ('group', models.OneToOneField(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.group')),
                ('db_alias', models.TextField(unique=True)),
                ('db_name', models.TextField()),
                ('db_host', models.TextField()),
                ('db_port', models.IntegerField()),
                ('db_user', models.TextField()),
                ('db_password', models.TextField()),
            ],
            options={
                'db_table': 'group_db_config',
                'managed': False,
            },
        ),
    ]
